version: "3"
services:


  service-a:
    image: service-a
    ports:
      - "8081:8081"  # Adjust ports as needed
    depends_on:
      - service-b
      
  service-b:
    image: service-b
    ports:
      - "8082:8082"  # Adjust ports as needed
    depends_on:
      - serice-c
  
  service-c:
    image: service-c
    ports:
      - "8083:8083"  # Adjust ports as needed

    

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      - COLLECTOR_OTLP_ENABLED=true